# -*- coding: utf-8 -*-
"""WATER_PURITY_CHECK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18fL_wB1AiX1Zdz0b32L1IweF9Ub3xuKn
"""

!pip install shap xgboost -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, IsolationForest
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, mean_squared_error
from sklearn.preprocessing import LabelEncoder

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print(df.isnull().sum())

df = df.fillna(df.mean(numeric_only=True))
df = df.drop_duplicates()

print("\nAfter cleaning:")
print(df.shape)

df['Color'] = np.random.choice(['Clear', 'Cloudy', 'Brown'], size=len(df))
df['Smell'] = np.random.choice(['None', 'Chlorine', 'Foul'], size=len(df))
df['Taste'] = np.random.choice(['Normal', 'Salty', 'Metallic'], size=len(df))
df['Source'] = np.random.choice(['Tap', 'Well', 'River'], size=len(df))

color_map = {'Clear':0, 'Cloudy':1, 'Brown':2}
smell_map = {'None':0, 'Chlorine':1, 'Foul':2}
taste_map = {'Normal':0, 'Salty':1, 'Metallic':2}
source_map = {'Tap':0, 'Well':1, 'River':2}

df['Color'] = df['Color'].map(color_map)
df['Smell'] = df['Smell'].map(smell_map)
df['Taste'] = df['Taste'].map(taste_map)
df['Source'] = df['Source'].map(source_map)

df['WQI'] = (
    df['ph'] * 0.2 +
    df['Hardness'] * 0.1 +
    df['Solids'] * 0.2 +
    df['Chloramines'] * 0.1 +
    df['Sulfate'] * 0.1 +
    df['Conductivity'] * 0.1 +
    df['Organic_carbon'] * 0.1 +
    df['Trihalomethanes'] * 0.1 +
    df['Turbidity'] * 0.1
)

df['WQI'] = (df['WQI'] - df['WQI'].min()) / (df['WQI'].max() - df['WQI'].min())

X = df.drop(['Potability', 'WQI'], axis=1)
y_class = df['Potability']
y_reg = df['WQI']

X_train, X_test, y_train_c, y_test_c = train_test_split(
    X, y_class, test_size=0.2, random_state=42
)

_, _, y_train_r, y_test_r = train_test_split(
    X, y_reg, test_size=0.2, random_state=42
)

clf = RandomForestClassifier(n_estimators=150, random_state=42)
clf.fit(X_train, y_train_c)

y_pred_c = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test_c, y_pred_c))
print(classification_report(y_test_c, y_pred_c))

reg = RandomForestRegressor(n_estimators=150, random_state=42)
reg.fit(X_train, y_train_r)

y_pred_r = reg.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test_r, y_pred_r))
print("RMSE:", rmse)

cm = confusion_matrix(y_test_c, y_pred_c)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(), cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

sns.histplot(df['WQI'], kde=True)
plt.title("WQI Distribution")
plt.show()

iso = IsolationForest(contamination=0.05)
df['Anomaly'] = iso.fit_predict(X)

sns.scatterplot(x=df.index, y=df['Solids'], hue=df['Anomaly'])
plt.title("Anomaly Detection")
plt.show()

print("\n💧 ENTER WATER DETAILS\n")

ph = float(input("Enter pH [0 - 14]: "))
Hardness = float(input("Enter Hardness [0 - 500]: "))
Solids = float(input("Enter Solids (TDS) [0 - 2000]: "))
Chloramines = float(input("Enter Chloramines [0 - 10]: "))
Sulfate = float(input("Enter Sulfate [0 - 500]: "))
Conductivity = float(input("Enter Conductivity [0 - 1000]: "))
Organic_carbon = float(input("Enter Organic Carbon [0 - 20]: "))
Trihalomethanes = float(input("Enter Trihalomethanes [0 - 150]: "))
Turbidity = float(input("Enter Turbidity [0 - 10]: "))

color = input("Enter Color (Clear/Cloudy/Brown): ")
smell = input("Enter Smell (None/Chlorine/Foul): ")
taste = input("Enter Taste (Normal/Salty/Metallic): ")
source = input("Enter Source (Tap/Well/River): ")

color_val = color_map.get(color, 0)
smell_val = smell_map.get(smell, 0)
taste_val = taste_map.get(taste, 0)
source_val = source_map.get(source, 0)

user_input = np.array([[ph, Hardness, Solids, Chloramines, Sulfate,
                        Conductivity, Organic_carbon, Trihalomethanes,
                        Turbidity, color_val, smell_val, taste_val, source_val]])

potability = clf.predict(user_input)[0]
wqi = reg.predict(user_input)[0]

print("\n🔹 RESULT")
print("Water Quality:", "SAFE ✅" if potability == 1 else "UNSAFE ❌")
print("WQI Score:", round(wqi, 3))

faults = []

if ph < 6.5 or ph > 8.5:
    faults.append("pH out of safe range")
if Solids > 500:
    faults.append("TDS too high")
if Turbidity > 5:
    faults.append("Turbidity too high")
if Chloramines > 4:
    faults.append("Chloramines too high")
if Sulfate < 250 or Sulfate > 500:
    faults.append("Sulfate out of range")
if Conductivity < 50 or Conductivity > 500:
    faults.append("Conductivity out of range")
if Organic_carbon > 10:
    faults.append("Organic carbon too high")
if Trihalomethanes > 80:
    faults.append("Trihalomethanes too high")

print("\n⚠️ FAULTS DETECTED")
if len(faults) == 0:
    print("No major faults")
else:
    for f in faults:
        print("-", f)

print("\n💡 RECOMMENDATIONS")

if Solids > 500:
    print("- Use RO filtration")
if Turbidity > 5:
    print("- Filter water before use")
if ph < 6.5:
    print("- Neutralize acidic water")
if ph > 8.5:
    print("- Treat alkaline water")
if potability == 0:
    print("- Not safe for direct drinking")
if len(faults) == 0:
    print("- Water is safe for consumption")

params = ['pH','TDS','Turbidity']
values = [ph, Solids, Turbidity]
limits = [7, 500, 5]

plt.figure(figsize=(6,4))
plt.bar(params, values)
plt.plot(params, limits, marker='o')
plt.title("User Water vs Safe Limits")
plt.show()

print("\n💧 ENTER WATER DETAILS\n")

ph = float(input("Enter pH [0 - 14]: "))
Hardness = float(input("Enter Hardness [0 - 500]: "))
Solids = float(input("Enter Solids (TDS) [0 - 2000]: "))
Chloramines = float(input("Enter Chloramines [0 - 10]: "))
Sulfate = float(input("Enter Sulfate [0 - 500]: "))
Conductivity = float(input("Enter Conductivity [0 - 1000]: "))
Organic_carbon = float(input("Enter Organic Carbon [0 - 20]: "))
Trihalomethanes = float(input("Enter Trihalomethanes [0 - 150]: "))
Turbidity = float(input("Enter Turbidity [0 - 10]: "))

color = input("Enter Color (Clear/Cloudy/Brown): ")
smell = input("Enter Smell (None/Chlorine/Foul): ")
taste = input("Enter Taste (Normal/Salty/Metallic): ")
source = input("Enter Source (Tap/Well/River): ")

color_val = color_map.get(color, 0)
smell_val = smell_map.get(smell, 0)
taste_val = taste_map.get(taste, 0)
source_val = source_map.get(source, 0)

user_input = np.array([[ph, Hardness, Solids, Chloramines, Sulfate,
                        Conductivity, Organic_carbon, Trihalomethanes,
                        Turbidity, color_val, smell_val, taste_val, source_val]])

potability = clf.predict(user_input)[0]
wqi = reg.predict(user_input)[0]

print("\n🔹 RESULT")
print("Water Quality:", "SAFE ✅" if potability == 1 else "UNSAFE ❌")
print("WQI Score:", round(wqi, 3))

faults = []

if ph < 6.5 or ph > 8.5:
    faults.append("pH out of safe range")
if Solids > 500:
    faults.append("TDS too high")
if Turbidity > 5:
    faults.append("Turbidity too high")
if Chloramines > 4:
    faults.append("Chloramines too high")
if Sulfate < 250 or Sulfate > 500:
    faults.append("Sulfate out of range")
if Conductivity < 50 or Conductivity > 500:
    faults.append("Conductivity out of range")
if Organic_carbon > 10:
    faults.append("Organic carbon too high")
if Trihalomethanes > 80:
    faults.append("Trihalomethanes too high")

print("\n⚠️ FAULTS DETECTED")
if len(faults) == 0:
    print("No major faults")
else:
    for f in faults:
        print("-", f)

print("\n💡 RECOMMENDATIONS")

if Solids > 500:
    print("- Use RO filtration")
if Turbidity > 5:
    print("- Filter water before use")
if ph < 6.5:
    print("- Neutralize acidic water")
if ph > 8.5:
    print("- Treat alkaline water")
if potability == 0:
    print("- Not safe for direct drinking")
if len(faults) == 0:
    print("- Water is safe for consumption")

params = ['pH','TDS','Turbidity']
values = [ph, Solids, Turbidity]
limits = [7, 500, 5]

plt.figure(figsize=(6,4))
plt.bar(params, values)
plt.plot(params, limits, marker='o')
plt.title("User Water vs Safe Limits")
plt.show()

params = ['pH','TDS','Turbidity']

values = [ph/14, Solids/500, Turbidity/5]
limits = [7/14, 500/500, 5/5]

plt.figure(figsize=(6,4))
plt.bar(params, values)
plt.plot(params, limits, marker='o')

plt.title("Normalized Water Quality Comparison")
plt.ylabel("Scaled Value (0–1)")
plt.show()

params = ['pH','TDS','Turbidity']
values = [ph/14, Solids/500, Turbidity/5]

colors = []
for v in values:
    if v <= 1:
        colors.append('green')
    else:
        colors.append('red')

plt.figure(figsize=(6,4))
plt.bar(params, values, color=colors)
plt.axhline(y=1, linestyle='--')
plt.title("Water Safety Level (Green = Safe, Red = Unsafe)")
plt.ylabel("Normalized Scale")
plt.show()

prob = clf.predict_proba(user_input)[0][1]

print("\n🔍 Confidence Level:", round(prob*100,2), "%")

importance = pd.Series(clf.feature_importances_, index=X.columns)
top_features = importance.sort_values(ascending=False).head(3)

print("\n🧠 Main Factors Affecting Result:")
for f in top_features.index:
    print("-", f)

if len(faults) == 0:
    severity = "Low Risk ✅"
elif len(faults) <= 2:
    severity = "Moderate Risk ⚠️"
else:
    severity = "High Risk ❌"

print("\n🚨 Risk Level:", severity)

print("\n💧 ENTER WATER DETAILS\n")

ph = float(input("Enter pH [0 - 14]: "))
Hardness = float(input("Enter Hardness [0 - 500]: "))
Solids = float(input("Enter Solids (TDS) [0 - 2000]: "))
Chloramines = float(input("Enter Chloramines [0 - 10]: "))
Sulfate = float(input("Enter Sulfate [0 - 500]: "))
Conductivity = float(input("Enter Conductivity [0 - 1000]: "))
Organic_carbon = float(input("Enter Organic Carbon [0 - 20]: "))
Trihalomethanes = float(input("Enter Trihalomethanes [0 - 150]: "))
Turbidity = float(input("Enter Turbidity [0 - 10]: "))

color = input("Enter Color (Clear/Cloudy/Brown): ")
smell = input("Enter Smell (None/Chlorine/Foul): ")
taste = input("Enter Taste (Normal/Salty/Metallic): ")
source = input("Enter Source (Tap/Well/River): ")

color_val = color_map.get(color, 0)
smell_val = smell_map.get(smell, 0)
taste_val = taste_map.get(taste, 0)
source_val = source_map.get(source, 0)

user_input = np.array([[ph, Hardness, Solids, Chloramines, Sulfate,
                        Conductivity, Organic_carbon, Trihalomethanes,
                        Turbidity, color_val, smell_val, taste_val, source_val]])

potability = clf.predict(user_input)[0]
wqi = reg.predict(user_input)[0]
confidence = clf.predict_proba(user_input)[0][1]

print("\n🔹 RESULT")
print("Water Quality:", "SAFE ✅" if potability == 1 else "UNSAFE ❌")
print("WQI Score:", round(wqi, 3))
print("Confidence:", round(confidence*100,2), "%")

faults = []

if ph < 6.5 or ph > 8.5:
    faults.append("pH out of safe range")
if Solids > 500:
    faults.append("TDS too high")
if Turbidity > 5:
    faults.append("Turbidity too high")
if Chloramines > 4:
    faults.append("Chloramines too high")
if Sulfate < 250 or Sulfate > 500:
    faults.append("Sulfate out of range")
if Conductivity < 50 or Conductivity > 500:
    faults.append("Conductivity out of range")
if Organic_carbon > 10:
    faults.append("Organic carbon too high")
if Trihalomethanes > 80:
    faults.append("Trihalomethanes too high")

print("\n⚠️ FAULTS DETECTED")
if len(faults) == 0:
    print("No major faults")
else:
    for f in faults:
        print("-", f)

print("\n💡 RECOMMENDATIONS")

if Solids > 500:
    print("- Use RO filtration")
if Turbidity > 5:
    print("- Filter before drinking")
if ph < 6.5:
    print("- Neutralize acidic water")
if ph > 8.5:
    print("- Treat alkaline water")
if potability == 0:
    print("- Not safe for direct drinking")
if len(faults) == 0:
    print("- Water is safe")

if len(faults) == 0:
    severity = "Low Risk ✅"
elif len(faults) <= 2:
    severity = "Moderate Risk ⚠️"
else:
    severity = "High Risk ❌"

print("\n🚨 Risk Level:", severity)

params = ['pH','TDS','Turbidity']
values = [ph/14, Solids/500, Turbidity/5]

colors = ['green' if v <= 1 else 'red' for v in values]

plt.figure(figsize=(6,4))
plt.bar(params, values, color=colors)
plt.axhline(y=1, linestyle='--')
plt.title("Water Safety Visualization")
plt.ylabel("Normalized Scale")
plt.show()

importance = pd.Series(clf.feature_importances_, index=X.columns)
top_features = importance.sort_values(ascending=False).head(3)

print("\n🧠 MAIN FACTORS:")
for f in top_features.index:
    print("-", f)

print("\n💧 ENTER WATER DETAILS\n")

ph = float(input("Enter pH [0 - 14]: "))
Hardness = float(input("Enter Hardness [0 - 500]: "))
Solids = float(input("Enter Solids (TDS) [0 - 2000]: "))
Chloramines = float(input("Enter Chloramines [0 - 10]: "))
Sulfate = float(input("Enter Sulfate [0 - 500]: "))
Conductivity = float(input("Enter Conductivity [0 - 1000]: "))
Organic_carbon = float(input("Enter Organic Carbon [0 - 20]: "))
Trihalomethanes = float(input("Enter Trihalomethanes [0 - 150]: "))
Turbidity = float(input("Enter Turbidity [0 - 10]: "))

color = input("Enter Color (Clear/Cloudy/Brown): ")
smell = input("Enter Smell (None/Chlorine/Foul): ")
taste = input("Enter Taste (Normal/Salty/Metallic): ")
source = input("Enter Source (Tap/Well/River): ")

color_val = color_map.get(color, 0)
smell_val = smell_map.get(smell, 0)
taste_val = taste_map.get(taste, 0)
source_val = source_map.get(source, 0)

user_input = np.array([[ph, Hardness, Solids, Chloramines, Sulfate,
                        Conductivity, Organic_carbon, Trihalomethanes,
                        Turbidity, color_val, smell_val, taste_val, source_val]])

potability = clf.predict(user_input)[0]
wqi = reg.predict(user_input)[0]
confidence = clf.predict_proba(user_input)[0][1]

print("\n🔹 RESULT")
print("Water Quality:", "SAFE ✅" if potability == 1 else "UNSAFE ❌")
print("WQI Score:", round(wqi, 3))
print("Confidence:", round(confidence*100,2), "%")

faults = []

if ph < 6.5 or ph > 8.5:
    faults.append("pH out of safe range")
if Solids > 500:
    faults.append("TDS too high")
if Turbidity > 5:
    faults.append("Turbidity too high")
if Chloramines > 4:
    faults.append("Chloramines too high")
if Sulfate < 250 or Sulfate > 500:
    faults.append("Sulfate out of range")
if Conductivity < 50 or Conductivity > 500:
    faults.append("Conductivity out of range")
if Organic_carbon > 10:
    faults.append("Organic carbon too high")
if Trihalomethanes > 80:
    faults.append("Trihalomethanes too high")

print("\n⚠️ FAULTS DETECTED")
if len(faults) == 0:
    print("No major faults")
else:
    for f in faults:
        print("-", f)

print("\n💡 RECOMMENDATIONS")

if Solids > 500:
    print("- Use RO filtration")
if Turbidity > 5:
    print("- Filter before drinking")
if ph < 6.5:
    print("- Neutralize acidic water")
if ph > 8.5:
    print("- Treat alkaline water")
if potability == 0:
    print("- Not safe for direct drinking")
if len(faults) == 0:
    print("- Water is safe")

if len(faults) == 0:
    severity = "Low Risk ✅"
elif len(faults) <= 2:
    severity = "Moderate Risk ⚠️"
else:
    severity = "High Risk ❌"

print("\n🚨 Risk Level:", severity)

params = ['pH','TDS','Turbidity']
values = [ph/14, Solids/500, Turbidity/5]

colors = ['green' if v <= 1 else 'red' for v in values]

plt.figure(figsize=(6,4))
plt.bar(params, values, color=colors)
plt.axhline(y=1, linestyle='--')
plt.title("Water Safety Visualization")
plt.ylabel("Normalized Scale")
plt.show()

importance = pd.Series(clf.feature_importances_, index=X.columns)
top_features = importance.sort_values(ascending=False).head(3)

print("\n🧠 MAIN FACTORS:")
for f in top_features.index:
    print("-", f)

X = df[['ph','Hardness','Solids','Chloramines','Sulfate',
        'Conductivity','Organic_carbon','Trihalomethanes','Turbidity']]

X = df[['ph','Hardness','Solids','Chloramines','Sulfate',
        'Conductivity','Organic_carbon','Trihalomethanes','Turbidity']]

y = df['Potability']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

import xgboost as xgb

clf = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

clf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

print("\n💧 ENTER WATER DETAILS\n")

ph = float(input("Enter pH [0 - 14]: "))
Hardness = float(input("Enter Hardness [0 - 500]: "))
Solids = float(input("Enter Solids (TDS) [0 - 2000]: "))
Chloramines = float(input("Enter Chloramines [0 - 10]: "))
Sulfate = float(input("Enter Sulfate [0 - 500]: "))
Conductivity = float(input("Enter Conductivity [0 - 1000]: "))
Organic_carbon = float(input("Enter Organic Carbon [0 - 20]: "))
Trihalomethanes = float(input("Enter Trihalomethanes [0 - 150]: "))
Turbidity = float(input("Enter Turbidity [0 - 10]: "))

user_input = np.array([[ph, Hardness, Solids, Chloramines, Sulfate,
                        Conductivity, Organic_carbon, Trihalomethanes,
                        Turbidity]])

prediction = clf.predict(user_input)[0]
prob = clf.predict_proba(user_input)[0]
confidence = max(prob)

print("\n🔹 RESULT")
print("Water Quality:", "SAFE ✅" if prediction == 1 else "UNSAFE ❌")
print("Confidence:", round(confidence*100,2), "%")

faults = []

if ph < 6.5 or ph > 8.5:
    faults.append("pH out of safe range")
if Solids > 500:
    faults.append("TDS too high")
if Turbidity > 5:
    faults.append("Turbidity too high")
if Chloramines > 4:
    faults.append("Chloramines too high")
if Sulfate < 250 or Sulfate > 500:
    faults.append("Sulfate out of range")

print("\n⚠️ FAULTS")
if len(faults) == 0:
    print("No major faults")
else:
    for f in faults:
        print("-", f)

print("\n💡 RECOMMENDATIONS")

if Solids > 500:
    print("- Use RO filtration")
if Turbidity > 5:
    print("- Filter water before drinking")
if ph < 6.5:
    print("- Neutralize acidic water")
if ph > 8.5:
    print("- Treat alkaline water")
if prediction == 0:
    print("- Not safe for drinking")
if len(faults) == 0:
    print("- Water is safe")

if confidence > 0.85:
    print("\n🚨 Risk Level: Low Risk ✅")
elif confidence > 0.7:
    print("\n🚨 Risk Level: Moderate Risk ⚠️")
else:
    print("\n🚨 Risk Level: Uncertain Prediction ❗")

params = ['pH','TDS','Turbidity']
values = [ph/14, Solids/500, Turbidity/5]

colors = ['green' if v <= 1 else 'red' for v in values]

plt.figure(figsize=(6,4))
plt.bar(params, values, color=colors)
plt.axhline(y=1, linestyle='--')
plt.title("Water Safety Visualization")
plt.show()

